export default {
  // app lifecycle
  APP_LOAD: 'APP_LOAD',
  ASYNC_START: 'ASYNC_START',
  ASYNC_END: 'ASYNC_END',
  REDIRECT: 'REDIRECT',
  SET_PAGE: 'SET_PAGE',

  // auth
  LOGIN: 'LOGIN',
  LOGIN_SAML: 'LOGIN_SAML',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST'
};
